### ISSUE TITLE
Eagle compatible Altium Exports

### ISSUE THREAD

**Issue by petervanderwalt** [circuitvalley/ttyMAY_linux_board#1]
Hi

Any chance you can export the design as per https://www.element14.com/community/thread/33590/l/how-to-import-altium-files-into-eagle?displayFullThread=true to help out those of us who want to learn from your work, but dont have Altium?

**Comment by circuitvalley** [comment]
ASCII Files has been added ,  please refer to read me how exactly files were exported

**Comment by petervanderwalt** [comment]
Thanks my friend!

(However these doesn't import hehe)

![fail](https://user-images.githubusercontent.com/31449271/35553368-513586cc-05a0-11e8-831f-647ccf6d6c36.PNG)
